"""add RSVP tables

Revision ID: 0774c9783bd9
Revises: 3f23be15b2bb
Create Date: 2025-08-08 23:58:36.560419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0774c9783bd9'
down_revision = '3f23be15b2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tm_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('start', sa.String(length=32), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tm_id')
    )
    op.create_table('event_attendee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('external_event_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(event_id IS NOT NULL) OR (external_event_id IS NOT NULL)', name='attend_has_one'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['external_event_id'], ['external_event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uniq_user_event'),
    sa.UniqueConstraint('user_id', 'external_event_id', name='uniq_user_external_event')
    )
    with op.batch_alter_table('event_attendee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_attendee_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_attendee_external_event_id'), ['external_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_attendee_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_attendee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_attendee_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_attendee_external_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_attendee_event_id'))

    op.drop_table('event_attendee')
    op.drop_table('external_event')
    # ### end Alembic commands ###
